# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Backup .env
      run: |
        if [-f .env]; then mv .env /temp/env_backup; fi
        
    - uses: actions/checkout@v4

    - name: Restore .env
      run: |
        if[-f /temp/env_backup] then mv /temp/env_backup .env; fi
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #  if it need then use only form github action secrets if not use the aws restore command
    # - run: |
    #     cat > .env << 'EOF'
    #     CLOUD_NAME=${{ secrets.CLOUD_NAME }}
    #     CLOUD_API_KEY=${{ secrets.CLOUD_API_KEY }}
    #     CLOUD_API_SERECT=${{ secrets.CLOUD_API_SERECT }}
    #     MAP_TOKEN=${{ secrets.MAP_TOKEN }}
    #     ATLASTDB_URL=${{ secrets.ATLASTDB_URL }}
    #     SECRET=${{ secrets.SECRET }}
    #     EOF
    - run: npm ci
    - run: npm run build --if-present
    - run: sudo pm2 restart backend
